yelp_clone/config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, shallow: true do
    resources :reviews do
      resources:endorsements
    end
  end

  root to: "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

yelp_clone/app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

yelp_clone/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, length: {minimum: 3}, uniqueness: true
  has_many :reviews, dependent: :destroy
  belongs_to :user

  def average_rating
    # return 'N/A' if reviews.none?
    # man = reviews.inject(0){|memo, review| memo + review.rating}
    # man/reviews.countaa
    reviews.average(:rating)
  end

  def average_rating
   return 'N/A' if reviews.none?
   (reviews.inject(0) {|memo, review| memo + review.rating} / reviews.length)
  end
end

yelp_clone/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "restaurant already reviewed"}
  has_many :endorsements
end

yelp_clone/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

end

yelp_clone/app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end
end

yelp_clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :authenticate_user!, :except => [:index, :show]
  def index
    @restaurants = Restaurant.all
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end

    if current_user.has_reviewed? @restaurant
      flash[:notice] = 'Restaurant already reviewed'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  def destroy
   @restaurant = Restaurant.find(params[:id])
   @restaurant.destroy
   flash[:notice] = 'Restaurant deleted successfully'
   redirect_to '/restaurants'
  end

end

yelp_clone/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(review_params)

    if @review.save
      redirect_to restaurants_path
    elsif @review.errors[:user]
      redirect_to restaurants_path, alert: 'Restaurant already reviewed'
    end
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating).merge(user: current_user)
  end

  def destroy
    @review = Review.find(params[:id])
    if current_user.reviews.include?(@review)
      @review.destroy
      # if @review.owned_by?(current_user)
      #   @review.destroy
      flash[:notice] = "Review deleted"
    else
      flash[:notice] = "Cannot delete review you have not added"
    end
      redirect_to restaurants_path
  end
end

yelp_clone/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

yelp_clone/app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

yelp_clone/app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

yelp_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>

<%= notice %>
<%= alert %>
<%= yield %>

</body>
</html>

yelp_clone/app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
    <p><%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %></p>
    <p><%= link_to "Rate and Review #{restaurant.name}", new_restaurant_review_path(restaurant) %></p>




    <% if restaurant.reviews.any? %>
      <ul>
        <% restaurant.reviews.each do |review| %>
          <li>
            <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
            <%= link_to "Delete review of #{restaurant.name}", review_path(review), method: :delete%>
            <%= link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link'%>
            <span class = "endorsements_count"> <%=review.endorsements.count%> </span> <%= 'endorsement'.pluralize(review.endorsements.count)%>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No reviews.</p>
    <% end %>
  <h5>Average rating: <%=star_rating(restaurant.average_rating.to_i)%> </h3>

  <% end %>

<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<a href="/restaurants/new">Add a restaurant</a>